name: build
on: [push, pull_request]
jobs:
  build:
    name: UTs ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: |
        go run build/make.go
        go run build/make.go --install

    - name: Unit tests
      # have to set this env var because of the util package init which requires it to be set
      env: 
        GAUGE_PROJECT_ROOT: ${{ github.workspace }}
      run: go run build/make.go --test --verbose
