name: functional-tests
on: [push, pull_request]
jobs:

  functional-tests:
    name: FTs ubuntu-latest
    runs-on: ubuntu-latest
    env:
      TAGS: js
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '15' # Need minimum Java 15 for text blocks in functional tests

      - name: Install Gauge
        run: curl -SsL https://downloads.gauge.org/stable | sh

      - name: Install gauge-js
        run: gauge install js

      - name: Install jira
        run: |
          go run build/make.go && go run build/make.go --distro
          gauge install jira --file $(ls -d bin/distros/*.zip)

      - name: Clone gauge-tests
        run: git clone --branch jira-wip https://github.com/agilepathway/spectacle-functional-tests

      - name: Run FTs
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        run: |
          cd spectacle-functional-tests
          ./gradlew clean jiraJsFT

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-logs-ubuntu-latest
          path: spectacle-functional-tests/logs
