name: FTs
on: [push, pull_request]
jobs:

  functional-tests:
    name: ${{ matrix.language }} ${{ matrix.os }} FTs 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # no windows because `go run build/make.go --distro` errors (can't find zip executable)
        os: [ubuntu-latest, macos-latest]
        language: [java]
        include:
        # macOS tends to be a bit slower, so only run all the other languages on Ubuntu
          - os: ubuntu-latest
            language: dotnet
          - os: ubuntu-latest
            language: js
          - os: ubuntu-latest
            language: python
          - os: ubuntu-latest
            language: ruby
      
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Gauge
        uses: getgauge/setup-gauge@master
        with:
          gauge-version: master
          gauge-plugins: ${{ matrix.language }}, html-report, screenshot

      - name: Install spectacle
        run: |
          go run build/make.go && go run build/make.go --distro
          gauge install spectacle --file $(ls -d bin/distros/*.zip)

      - name: Run FTs
        run: |
          cd functional-tests
          ./gradlew clean ${{ matrix.language }}FT

      - name: Upload logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: ft-logs-ubuntu-latest
          path: functional-tests/logs
